# Generated by Django 5.1.4 on 2025-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_blogpage_likes_remove_blogpage_views"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpagegalleryimage",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
            },
        ),
        migrations.AddField(
            model_name="blogpagegalleryimage",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
