# Generated by Django 5.1.4 on 2025-01-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogpagegalleryimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="subtitle",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
