# Generated by Django 5.1.4 on 2025-01-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_blogindexpage_blogpage_blogpagegalleryimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
