# Generated by Django 5.1.4 on 2025-01-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpage_likes_blogpage_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="views",
        ),
    ]
